export const AVATARS: { emoji: string; label: string }[] = [
  // Botánico
  { emoji: "🌿", label: "Hoja" },
  { emoji: "🌸", label: "Cerezo" },
  { emoji: "🌻", label: "Girasol" },
  { emoji: "🌷", label: "Tulipán" },
  { emoji: "🌹", label: "Rosa" },
  { emoji: "🍀", label: "Trébol" },
  { emoji: "🌵", label: "Cactus" },
  { emoji: "🪴", label: "Maceta" },
  { emoji: "🍃", label: "Brisa" },
  // Animales cálidos
  { emoji: "🦊", label: "Zorro" },
  { emoji: "🐝", label: "Abejita" },
  { emoji: "🐢", label: "Tortuga" },
  { emoji: "🦔", label: "Erizo" },
  { emoji: "🐰", label: "Conejo" },
  { emoji: "🐱", label: "Gato" },
  { emoji: "🐶", label: "Perro" },
  { emoji: "🦉", label: "Búho" },
  { emoji: "🐻", label: "Oso" },
  { emoji: "🦌", label: "Ciervo" },
  { emoji: "🐧", label: "Pingüino" },
  // Naturaleza / clima
  { emoji: "☀️", label: "Sol" },
  { emoji: "🌙", label: "Luna" },
  { emoji: "⭐", label: "Estrella" },
  { emoji: "🌟", label: "Brillo" },
  { emoji: "✨", label: "Chispas" },
  { emoji: "🌊", label: "Ola" },
  { emoji: "🔥", label: "Fuego" },
  // Comida / hogar
  { emoji: "☕", label: "Café" },
  { emoji: "🍯", label: "Miel" },
  { emoji: "🍵", label: "Té" },
  { emoji: "🥐", label: "Croissant" },
  { emoji: "🧁", label: "Cupcake" },
  { emoji: "🍓", label: "Frutilla" },
  { emoji: "🥑", label: "Palta" },
  { emoji: "🍋", label: "Limón" },
  // Objetos cálidos
  { emoji: "🕯️", label: "Vela" },
  { emoji: "📚", label: "Libros" },
  { emoji: "🎨", label: "Arte" },
  { emoji: "🎸", label: "Guitarra" },
  { emoji: "🪶", label: "Pluma" },
];
